---
- name: Remove previous docker installation
  apt:
    name: "{{item.package}}"
    state: absent
  with_items: "{{docker_cleanup_packages_Ubuntu}}"

- name: Install prerequisite packages
  apt:
    name: "{{item.package}}"
    state: present
  with_items: "{{docker_prerequisite_packages_Ubuntu}}"

- name: Import Docker CE repository gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 
- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add User to Docker Group
  shell: gpasswd -a "{{user_add_to_docker_group}}" docker

- name: Restart Docker
  service: 
    name: docker
    state: restarted

