- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws.yml
    # - vars/vault.yml
  tasks:
    - import_tasks: tasks/ec2.yml
      tags: [ec2]

    - import_tasks: tasks/caller-id.yml
      tags: [caller-id]

    - import_tasks: tasks/test.yml
      tags: [test]