---
scala_version: "2.11"
kafka_version: "0.10.2.1"

install_dir: "/opt"
symlink_name: "kafka"
kafka_name: "kafka_{{ scala_version }}-{{ kafka_version }}"
kafka_download_url: "http://ftp.yz.yamagata-u.ac.jp/pub/network/apache/kafka/{{ kafka_version }}/{{ kafka_name }}.tgz"
