---
- name: Install tree cmd
  apt: name=tree

- name: Install unzip cmd
  apt: name=unzip

# For the xml module
- name: Install python-lxml
  apt: name=python-lxml state=latest update_cache=yes force=yes

- name: Setting hosts
  lineinfile: >- 
    state=present 
    create=yes
    dest='/etc/hosts' 
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^192.168.33.101'
      line: '192.168.33.101 node1'
    - regexp: '^192.168.33.102'
      line: '192.168.33.102 node2'
    - regexp: '^192.168.33.10'
      line: '192.168.33.10 master'

- name: Install tshark cmd
  apt: name=tshark