---
- name: Install tree cmd
  apt: name=tree

- name: Install unzip cmd
  apt: name=unzip

- name: Setting hosts
  lineinfile: >- 
    state=present 
    create=yes
    dest='/etc/hosts' 
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^192.168.43.11'
      line: '192.168.43.11 node1'
    - regexp: '^192.168.43.12'
      line: '192.168.43.12 node2'
    - regexp: '^192.168.33.10'
      line: '192.168.33.10 master'
