---
- name: Add apt repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install java
  apt: name={{item}} state=latest update_cache=yes force=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
