---
- name: ensure kafka present
  unarchive:
    remote_src: yes
    src: "{{ kafka_download_url }}"
    dest: "{{ install_dir }}"

- name: ensure symlink present
  file:
    src: "{{ install_dir }}/{{ kafka_name }}"
    dest: "{{ install_dir }}/{{ symlink_name }}"
    mode: 0755
    state: link

- name: setting server.properties
  lineinfile: >- 
    state=present 
    create=yes
    dest='{{ install_dir }}/{{ symlink_name }}/config/server.properties' 
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^broker.id='
      line: 'broker.id={{ kafka_broker_id }}'
    - regexp: '^listeners='
      line: 'listeners=PLAINTEXT://{{ my_ipv4_addr }}:9092'
    - regexp: '^zookeeper.connect='
      line: 'zookeeper.connect={{ master_ipv4_addr }}:2181'

