---
- hosts: workers

  pre_tasks:
    - name: Get ansible_user home dir
      shell: "getent passwd {{ ansible_env.SUDO_USER }} | awk -F: '{print $6}'"
      register: ansible_home_result

    - name: Set ansible_home var
      set_fact: ansible_home='{{ansible_home_result.stdout}}'

  sudo: yes
  roles:
    - common
    - java-install
    - docker-ce-install
    - kafka-install
    - zabbix-agent-install
    - hadoop-install
